### ISSUE TITLE
Activation email for Padlock cloud sync is just not being sent

### ISSUE THREAD

**Issue by DiGwork** [MaKleSoft/padlock#10]
Attempting to Synchronise with padlock cloud on my desktop device but the activation email is just not being sent. I have tried disconnecting and reconnecting but the email is just not being sent to my email account.

**Comment by MaKleSoft** [comment]
Hi @DiGwork, thanks for the heads up! I was just experiencing the same thing and checked the server configuration. Turns out some environment variables weren't set correctly after a server migration. Should be back to normal now. Let me know if you encounter any more issues!

**Comment by DiGwork** [comment]
Thanks Martin
