### ISSUE TITLE
Gulp compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by KentShikama** [MaKleSoft/padlock#101]
Assuming popd in the postinstall is simply going back a directory, I'm now facing the problem where gulp compile throws an error

```
> gulp compile

[19:50:54] Using gulpfile ~/Documents/padlock/gulpfile.js
[19:50:54] Starting 'compile'...
[19:50:54] Finished 'compile' after 136 ms

events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeScript error: app/src/core/util.ts(67,29): Error TS7006: Parameter 'baseClass' implicitly has an 'any' type.

```

Do I need a specific version of npm or node?

**Comment by MaKleSoft** [comment]
This is a typescript compilation error. I wonder why this didn't show up on my machine. I'll look into it!

**Comment by MaKleSoft** [comment]
Hm, turns out `gulp compile --watch` doesn't spit out compiler warnings. This should fix it: https://github.com/MaKleSoft/padlock/commit/f3de9ec1ec569d5aaba9abf91edf496362606e12

**Comment by MaKleSoft** [comment]
Also made the task throws on compiler errors in watch mode: https://github.com/MaKleSoft/padlock/commit/5454dc06efbb474f08bde6ed577f1d21ce52a544
