### ISSUE TITLE
Allow to select where encrypted passwords are stored

### ISSUE THREAD

**Issue by Moxinilian** [MaKleSoft/padlock#106]
Hello, this is a feature request.
It could be interesting to be able to choose in what folder we want to store the encrypted passwords in the desktop version. For example, one could choose their OneDrive folder on Windows to store the passwords, and thus have it be automatically synched to the cloud for free.
Have a nice day.

**Comment by MaKleSoft** [comment]
This will definitely be coming in some form in one of the 2.x releases. We already made a step towards this by migrating storage from browser-internal `localStorage` to saving the data directly to the file system. There are still some open UX questions to be figured out but we'll definitely revisit this soon.

**Comment by TizianoPerrucci** [comment]
@MaKleSoft this is another important one, or at least can we find some documentation where the secret file is stored?

**Comment by MaKleSoft** [comment]
https://github.com/MaKleSoft/padlock/pull/159 Should fix this, but still needs testing. If anybody could build and test this that would be a great help, especially on Windows and Linux.

**Comment by MaKleSoft** [comment]
@Moxinilian @TizianoPerrucci This has been implemented in the latest beta release, in case you want to test it now!
