### ISSUE TITLE
Support for OTP or U2F

### ISSUE THREAD

**Issue by dickolsson** [MaKleSoft/padlock#109]
Thanks for an awesome 2.0 release!

The only missing feature (for the paranoid) is two-factor authentication. Would be really good to have either regular OTP or U2F support. I'd prefer U2F/FIDO support so one could use a YubiKey or TREZOR device.

Cheers!

**Comment by MaKleSoft** [comment]
Hi @dickolsson. Thanks for your feedback! As I've explained in https://github.com/MaKleSoft/padlock/issues/24, I don't see how implementing 2FA would add any security compared to our current approach. If you disagree, feel free to take up your case there ;) Closing this as duplicate.

**Comment by dickolsson** [comment]
Thanks, I will post my thoughts in that thread that has more context! Cheers!

**Comment by iwkse** [comment]
Hi, I'm interested in OTP/2FA not in terms of security improvement, which already works with sending email but more as a matter of usability. Having freeOTP or google authenticator on a mobile would make the process smoother and easier.
The actual link is broken.
Nothing in such direction?

**Comment by MaKleSoft** [comment]
@iwkse This is a fairly old issue and our stance on 2FA as an additional security layer has changed since (mostly because the new architecture in Padloc 3 makes it much more feasible). So additional 2FA methods aside from email are definitely planned.
