### ISSUE TITLE
Encrypted backup import error

### ISSUE THREAD

**Issue by prestontallen** [MaKleSoft/padlock#112]
Exported encrypted backup from chrome app (v2) and attempted to import into OSx app (also v2). Getting an error "Failed to recognize file format." File name is padlock-export.pls

<img width="802" alt="screen shot 2017-09-08 at 9 27 06 am" src="https://user-images.githubusercontent.com/5691166/30216302-301f8918-9478-11e7-8c58-be90cbadf305.png">

Chrome Version 60.0.3112.113 (Official Build) (64-bit)
OSx Version 10.12.6 (16G29)

**Comment by MaKleSoft** [comment]
Thanks for reporting this! Why this didn't show up in the tests is beyond me. Managed to reproduce it and will fix asap. In the meantime, you can use the export/import to/from clipboard.
