### ISSUE TITLE
Add support for iOS LocalAuthentication (TouchID)

### ISSUE THREAD

**Issue by mandusm** [MaKleSoft/padlock#113]
It would be great we could add support for iOS Biometric Local Auth and not need to type in the master password each time to unlock. 

https://developer.apple.com/documentation/localauthentication

**Comment by MaKleSoft** [comment]
Hi @mandusm. Thanks for your feedback! There already is an issue on this topic: https://github.com/MaKleSoft/padlock/issues/21
Feel free to weigh in there!
