### ISSUE TITLE
Nice Update

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#116]
I had to make an issue to thank you for the update.

Now that's a nice update, at first I wasn't digging the 2.0 I liked the other version more. But now it's really nice with the each field name being right under each entry and easy to copy by just clicking the field name.

**Comment by eorroe** [comment]
You should update the screenshots on this page though: https://padlock.io/news/v2.0-released/

**Comment by MaKleSoft** [comment]
Hey @eorroe, thanks for the kind words! I'm assuming you're talking about the 2.1 release? There is actually a separate article for that: https://padlock.io/news/v2.1-released/ (meaning the screenshots in the article you were linking to are still accurate ;)
