### ISSUE TITLE
Add option to disable showing password on hover

### ISSUE THREAD

**Issue by dickolsson** [MaKleSoft/padlock#117]
One thing that I really liked with 2.0.0 was that all passwords were easy to copy to clipboard from the listing, without exposing the passwords on the screen at all.

But in 2.1.0 this changed. When hovering in order to copy to clipboard my password is shown on the screen. And even though I have very long and random passwords, as well a privacy screens on all my devices, this feels very insecure.

A targeted attack become much easier by someone just peeking over your shoulder etc.

**Comment by MaKleSoft** [comment]
@dickolsson Thanks for your feedback! You make a valid point. However, I think there is also value in being able to "peek" at the value in case you want to type it manually on another device. Let's make this configurable so people can decide for themselves which behavior they prefer.

**Comment by dickolsson** [comment]
Great idea to make this configurable! 👍

**Comment by pwasiewicz** [comment]
Waiting for this feature to be implemented as soon as possible - I was quite shocked when It turned out that it works in this way. As for now, I am not able to login to a site when someone is with me. 

Meanwhile, I will add this feature for my local own build :)

**Comment by pwasiewicz** [comment]
@MaKleSoft I have created branch with implemented this feature on my fork: https://github.com/pwasiewicz/padlock/commit/2bcbd546a2a8a86cfa6cec4e36b3b47d4c6fff89
What about Merge Request?

**Comment by MaKleSoft** [comment]
@pwasiewicz  Sure, go for it!

**Comment by MaKleSoft** [comment]
Fixed in #124
