### ISSUE TITLE
Any plan to implement padlock an easy automatic management of passwords?

### ISSUE THREAD

**Issue by dumle29** [MaKleSoft/padlock#12]
So the tilte may be a bit bad, but I'll try and explain it a bit better here in the comments.
I'd very much like this to work in the following way:

1: I got to website A, where I'm not currently logged in. I click the padlock extension in the top right of chrome, and it prompts me for my master password. As soon as I've entered that, it shows me my credentials for the page that I'm currently on, as well as tries to automatically fill the appropriate fields. 

2: I go to a website where I'm currently not using padlock / haven't registered. I go to register, and after typing in all my information except password, I hit the padlock icon. It asks me for the master pass, and after entering it, It tells me it has no record for the current website. Do I want to make a new one? I hit create new, hit randomize password and paste, and it makes a strong password, shows it and attempts to paste it in the correct box.

As a site note, it'd be nice to have a few options for the randomly generated passwords. Something like checkboxes for

* A-Z
* a-z
* 0-9
* And a field for special characters. Default value being all of them.

I'll take a look at the source as well, and see if I'm capable of doing these things myself. I doubt it though, as I haven't made any extention yet :/

**Comment by MaKleSoft** [comment]
Hi @dumle29,

your suggestions sound amazing and I've been thinking about this myself, but implementing this would introduce a level of complexity that I've been purposefully trying to avoid. Sometimes it's hard to say no to awesome ideas like this but the top priority for this project is to avoid clutter and unnecessary complexity at all costs and focus on security and usability instead. If you still want to take a shot at this, please do! I definitely encourage people to mess around with the source code and see what they come up with. Just be aware that your changes might not be merged into the main project. Also, I'm currently working on a major refactor of the project, so you might want to hold off on making any changes for a couple of days.
