### ISSUE TITLE
Clear clipboard after a certain time

### ISSUE THREAD

**Issue by MaKleSoft** [MaKleSoft/padlock#120]
After copying a field value to the clipboard, that value should optimally not hang around indefinitely. Make sure that the system clipboard is cleared after a certain amount of time has passed.

**Comment by dickolsson** [comment]
I'd love to see this feature implemented. Either as a time-based functionality, or even as trivial as having a discrete button on either or both of (a) the unauthenticated screen or (b) in the button bar when authenticated.

Another simple idea is to simply clear the clipboard when the user actively chooses to lock Padlock (i.e. when clicking the lock button).
<img width="532" alt="screen shot 2018-01-05 at 10 20 25" src="https://user-images.githubusercontent.com/112085/34602966-440071e4-f202-11e7-9922-ca402710e9b1.png">

Although this isn't something that is inherent to Padlock, it seems like it's one of those big and critical vectors that Padlock can and should address.

**Comment by MaKleSoft** [comment]
@dickolsson I hear you. Will try to address this in the next release.

**Comment by MaKleSoft** [comment]
This is what it's going to look like in v2.5
![padlock-clipboard](https://user-images.githubusercontent.com/1270940/35919234-9e3a8b78-0bfb-11e8-92b9-d4c9779b874e.png)
