### ISSUE TITLE
Cannot pair device with custom server on IOS app

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#125]
When trying to pair device with custom cloud server, I got nessage that "Something went wrong. Please try again later.". Pairing with official padlock cloud works fine. When using the same custom server with desktop app, everything works fine.

IOS 10.3.3

**Comment by MaKleSoft** [comment]
Are you using the `cors` flag? See https://github.com/MaKleSoft/padlock-cloud/#chrome-app-fails-to-connect-to-custom-server

**Comment by pwasiewicz** [comment]
Tried to run server with and w/o `--cors` flag - the same result, cannot pair device from IOS app.

**Comment by MaKleSoft** [comment]
Are you using a self-signed certificate by any chance? What does your server log say?

**Comment by pwasiewicz** [comment]
Cloudflare Certificate is used. You can check here: https://cloud.pewudev.pl/
Logs are empty - there is no any record of login trial neither ERR or LOG file.

**Comment by pwasiewicz** [comment]
Ok works - my bad. Forgot that command line args don't work while config file is provided. When enabled CORS, everything seems to be working.
