### ISSUE TITLE
Hide by default all passwords

### ISSUE THREAD

**Issue by TizianoPerrucci** [MaKleSoft/padlock#126]
Hi, this is a feature request.

It is connected to #117 but the idea is that passwords should always be hidden unless the user really wants to see them.

Other applications solves this issue using two icons next to the hidden password: one for copying to the clipboard and one for displaying it.

You can't use this tool if you are on a screen sharing session because you could accidentally click on one item which will display the item detailed view.

**Comment by pwasiewicz** [comment]
Implementing this feature in the fork: https://github.com/pwasiewicz/padlock/tree/feature/maskable-field

**Comment by MaKleSoft** [comment]
I've been thinking about a way to do this without adding another UI element. On way would be to hide values unless the user is currently editing the field (and by editing I mean has put focus on the corresponding input by clicking it). This would be intuitive (user would basically just click on the masked value), require a minimal amount of code and not require an additional button. @pwasiewicz How were you thinking of approaching it?

**Comment by pwasiewicz** [comment]
@MaKleSoft it is implemented by the following commit: https://github.com/pwasiewicz/padlock/commit/7702378c2adf5a1d982cf80e517686f3a57ae506 - value is shown on focus.

Another commit introduces working button enables / disables this feature but I haven't managed to serialize additional flag in `field` record (https://github.com/pwasiewicz/padlock/commit/42a6f656127042cced62f6521e9046ab5114c4fc). 

Anyway - indeed, fields could be masked by default w/o any additional button - disabling this option could be somehow.. unsecure ;)

**Comment by MaKleSoft** [comment]
> So my code introduces button for each field that allows to mask value it when focus is lost

Like I said, I would like to avoid introducing another button if possible.

> I think that field with password title could have this feature enabled by default and the other ones - disabled.

I've been trying to avoid treating the password field different from other fields to keep the architecture as generic and simple as possible. At some point there might be some form of categorisation through pattern matching and simple heuristics but I'd like to give it more thought before going down that route. If we're hiding field values by default, we should do that for all fields for now.

**Comment by pwasiewicz** [comment]
Ok, I see. 
So the only one commit I have referenced could be considered as feature implementation.
I am creating pull request tommorrow.

**Comment by TizianoPerrucci** [comment]
what about this:

when creating a new record for each field we have a bunch of icons on the right for some common operations 
![image](https://user-images.githubusercontent.com/323648/31321645-452a3438-ac89-11e7-99b7-6bc7715d20db.png)

Now we could add another icon like 
![image](https://user-images.githubusercontent.com/323648/31321654-596a327c-ac89-11e7-87e7-38c44ae6a0ef.png)
and 
![image](https://user-images.githubusercontent.com/323648/31321660-685a5cda-ac89-11e7-92cc-8d994d5fde91.png)
to define if the field hold sensible information or not (`password` fields or any variation of it will of course have the lock closed by default)

**Comment by TizianoPerrucci** [comment]
> I've been trying to avoid treating the password field different from other fields to keep the architecture as generic and simple as possible
How can you treat in the same way sensible and non-sensible information ?

**Comment by MaKleSoft** [comment]
> How can you treat in the same way sensible and non-sensible information ?

We're treating all data as sensitive information.
