### ISSUE TITLE
Adding a custom field and then switching records results in unexpected behaviour

### ISSUE THREAD

**Issue by Yikal** [MaKleSoft/padlock#128]
Steps to reproduce:

1. Have at least two records
2. Add a custom field to one of the records (enter title and content)
3. Switch to another record

Result: The custom field is added to the second record
Expected: The custom field is added to the first record

(Tested on Windows 10 stable build)

**Comment by MaKleSoft** [comment]
@Yikal Wow, good catch. Just to confirm, this only happens when clicking directly on another record while focus is still on the 'new field' input, correct? Clicking anywhere else first or using tab to move focus from the input correctly saves the new field to the current record?

**Comment by Yikal** [comment]
Yes, I can confirm that.
It only happens when directly clicking on another record while still editing the new text field.

**Comment by MaKleSoft** [comment]
Got it. Expect this to be fixed in the next release.
