### ISSUE TITLE
Autofill passwords

### ISSUE THREAD

**Issue by anandubajith** [MaKleSoft/padlock#13]
Is there an option to do that ?
It would be very nice if you added that :+1:

**Comment by MaKleSoft** [comment]
Hey @anandubajith, thanks for the suggestion! This is a commonly requested feature but probably not something that will find it's way into Padlock anytime soon. The main goal of Padlock is to keep the level of complexity to a minimum to guarantee as simple a user experience as possible and to ensure the best code maintainability. Auto-filling passwords would require relatively deep platform integration and some fuzzy logic that would introduce a level of complexity that we've been consciously been trying to avoid.

**Comment by anandubajith** [comment]
![2015-08-02-175300_1366x768_scrot](https://cloud.githubusercontent.com/assets/3852827/9026089/5669ac52-393f-11e5-86ca-bd9656b379d1.png)

if you could make the app like a dropdown(see screenshot) then i could live without the autofill feature..

**Comment by MaKleSoft** [comment]
That's an interesting suggestion... Maybe just a lightweight view for copying/pasting? I'll think about it... Thanks!

**Comment by anandubajith** [comment]
The lightweight view seems to be a good addition.

**Comment by matheuslessarodrigues** [comment]
Hi! There is also the option of just doing the "AutoType" like the KeePass does. It is not autofill, but like a macro that <types username> "tab" <types password> "enter". What do you say? :)

**Comment by MaKleSoft** [comment]
@matheuslessarodrigues It's hard to say no to great suggestions like this but again, this would require a level of system integration that I would like to avoid if necessary. I also feel that it does not add enough value over a simple copy-paste flow to justify the added complexity. I do appreciate the suggestions though! Please keep 'em coming!

**Comment by nickbudi** [comment]
+1, I didn't realize there wasn't an autofill feature until I noticed it was a google app rather than extension. I'm looking for an alternative to lastpass and this would be so perfect if it had some basic browser integration.

**Comment by MaKleSoft** [comment]
Because this keeps coming up (although not as often as you would expect) - here is an interesting article that goes into why browser integration for password managers is generally a bad idea:
https://www.networkworld.com/article/3183675/security/stop-using-password-manager-browser-extensions.html

**Comment by Phenek** [comment]
For my concern browser extensions should only work as an extension of the real padloc Desktop App.
The browser should not have access to all passwords, it should only see if the vault is lock or unlock and only ask for the asked password, and fill it with biometry confirmation only.

Desktop App ⇔ Browser Extension ⇔ AutoFill Password ⇔ Biometry

**Comment by chrisonline** [comment]
In Enpass I see this screen directly in the web form:
![image](https://user-images.githubusercontent.com/2077218/209355850-4db58114-6a10-4db4-b256-0650f0e5f120.png)

After unlock I see suggestions:
![image](https://user-images.githubusercontent.com/2077218/209355974-a76f6e69-54ed-425f-b33f-ed4c35462fb0.png)

After clicking the suggestion, the fields are automatically filled.

Is something like this planned?

**Comment by BrunoBernardino** [comment]
@chrisonline if you right click on an input and Padloc has items for the current URL, they'll show up as options, and click them will fill that field. That already exists, yes.

**Comment by chrisonline** [comment]
> @chrisonline if you right click on an input and Padloc has items for the current URL, they'll show up as options, and click them will fill that field. That already exists, yes.

Yes I know, but I need here multiple clicks.
Right click on username field select padloc and username.
Right click on password field select padloc and password.

In Enpass I click only ones and both fields are filled.
