### ISSUE TITLE
Exporting part of records

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#132]
I think that availability of exporting records with specified tag(s) would be very useful.
Consider that I have password stored for my client that all are tagged and I'd like to share all of it with my collaborators.  Now, I need to export all records and then filter it.

**Comment by pwasiewicz** [comment]
@MaKleSoft what about makingnew  switch inside settings: "Export only visible records"? In my opinion it would be the easiest implementation - I filter collection by a tag f.e and then export only what is on the list. 

The major change in the source code would be sharing `filterByString` method between `list-view.html` and `settings-view.html` as well as `_filterString` property.

What about that?

**Comment by MaKleSoft** [comment]
Partial exports is something I've had on my list for a while but I've been planning to combine it with a multi-select feature in the list view which will allow for a more flexible use. A user could then select a number of records from the list view and then choose from a context menu what to do with them. 'Delete' and 'Export' are the most obvious options but I'm sure we can come up with more. A 'select all filtered' option would make exporting a specific subset of records very easy. I.e.:

1. enter multi-select mode
2. filter (for example by category)
3. select all 
4. export

Implementing a multi-select mode is the biggest challenge here. There are a couple of UX details I still have to figure out but I'll probably tackle this soon.

**Comment by MaKleSoft** [comment]
Revolved in https://github.com/MaKleSoft/padlock/commit/a66409e2224dfafc360bfdadca228f7f60172d4f

**Comment by MaKleSoft** [comment]
@pwasiewicz Can you pull the latest and see if the new multi-select / partial export feature does what you need?

**Comment by pwasiewicz** [comment]
@MaKleSoft done it already. Looks great - nice UX and works as expected. Thanks!

**Comment by MaKleSoft** [comment]
@pwasiewicz Good to hear! So you had no trouble entering multi-select mode and finding the 'select all' button?
