### ISSUE TITLE
Add sorting options

### ISSUE THREAD

**Issue by AlexMarvelo** [MaKleSoft/padlock#134]
I like Padlock so much
But sorting features are weak for me. When account grew up to 200 items, sorting options like "last changed" and "last added" would be very useful.

**Comment by MaKleSoft** [comment]
@AlexMarvelo I hear you. There probably won't be a way to change the order of list in general but there are plans to add a "recent" section at the top of the list that will contain recently used, added or edited records.

As an aside, have you tried using the filter function? I find that it's a pretty fast way to find records, especially if used with the `ctrl/cmd + f` keyboard shortcut on the desktop. I never even scroll - simply hit `cmd + f` type a few characters and there it is. Even on mobile I think it's way faster than scrolling or even using the section selector.

**Comment by AlexMarvelo** [comment]
Yes, I also use filter as usual.
Once I had a problem, when I accidently changed the title of item and didn't see the updated value. Then I had to scroll the whole list to find it

Feature with recent modified items would help with my problem, so I think it's great idea

**Comment by MaKleSoft** [comment]
Resolved: https://github.com/MaKleSoft/padlock/commit/33d03f6dc6cdf29ec45bedb6e866cff79beb7eb5

The list view now features a "Recently Used" section with the 3 records that were last used order edited. @AlexMarvelo Does this work for you?

![-users-martin-workspace-padlock-app-index html iphone 6](https://user-images.githubusercontent.com/1270940/32263795-ac4f97b6-bedb-11e7-9cd1-c1ea6c7131e2.png)

**Comment by AlexMarvelo** [comment]
@MaKleSoft Yes, tested on mac build
Good job :thumbsup:
