### ISSUE TITLE
Padlock not showing after launching from Windows 10 Chrome apps panel

### ISSUE THREAD

**Issue by DiGwork** [MaKleSoft/padlock#14]
Hi I have two machines running Windows 10, but just one has suddenly developed a problem launching Padlock. 
After launching Padlock from Chrome app panel the browser blinks and becomes a background window and then nothing no Padlock window. Yet when I hover over padlock icon, that is underlined shows window is open, the open app shows in the popup but nothing when you select it.

Also if you use the Task View icon to show all open windows the padlock window shows but if you select it nothing?
I have tried restarting machine.
I have tried reinstalling Chrome
nothing has worked.
Oh and it also doesn't make a difference how you launch Padlock. I have docked the icon on the desktop launchbar and launching that way also doesn't work.
OK also tried deleting Padlock from Chrome and reinstalling no luck.

**Comment by MaKleSoft** [comment]
@DiGwork Does this problem still persist? I think I remember that you mentioned in an email that this has resolved itself. If so, please close this issue. Thanks!
