### ISSUE TITLE
Records icons

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#140]
Let's introduce icons to records. There is bunch of them in [Font Awesome](http://fontawesome.io/).
It's easy, css-based frameowork to use icons in app or website.  Possible UI design:

![Preview](https://image.ibb.co/n3SjtG/padlock_icons.jpg "Preview")

Icons could be selected just like category  (dropdown with search-field).

**Comment by dickolsson** [comment]
Personally I love the clean look and feel, with few or no icons. I'm not sure if this adds or improve on the user experience?

I find myself using the search which quickly narrows down the records anyway, without the need for icons to enhance the scan-ability of the list.

**Comment by MaKleSoft** [comment]
I agree with @dickolsson. I find that record-specific icons would be more of a gimmick than a feature, really, and I don't think they would add much value other than potentially make it look a little prettier. I'm closing this for now. Maybe we'll revisit the idea at a later point.
