### ISSUE TITLE
More meanigful message, when cannot connect to custom cloud server

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#143]
When my cloud went down, padlock started showing message "_something went wrong_"  every minute on any view - it took me while to figure out, that my cloud server was down (I was rather thinking about bug inside app).

I think that mentioned scenario could be detected and more meaningful message should be displayed to end-user: 

> Unable to access cloud server for sync proccess. Check your internet connection or server availability.

**Comment by MaKleSoft** [comment]
Most recent version show distinct error message in case of a failed connection (see screenshot). I think this should be a sufficient indicator that the custom Padlock Cloud instance may be down. @pwasiewicz Let me know if that works for you!  
![-users-martin-workspace-padlock-app-index html iphone 6](https://user-images.githubusercontent.com/1270940/38177036-2c9f4efa-35d0-11e8-8ba0-ed50b01fdfb4.png)

**Comment by pwasiewicz** [comment]
Closing the issue - after update, everything works flawlessly ;)
