### ISSUE TITLE
Complie failed on Linux

### ISSUE THREAD

**Issue by bbx963872** [MaKleSoft/padlock#144]
Hi!
I tried to compile padlock on Ubuntu 16.04 LTS. However, after the "npm run build:linux" command, an error occurs as follows:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padlock@2.3.1 build:linux: `gulp build --linux --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the padlock@2.3.1 build:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-21T23_10_10_734Z-debug.log
**The log files:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:linux' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild:linux', 'build:linux', 'postbuild:linux' ]
5 info lifecycle padlock@2.3.1~prebuild:linux: padlock@2.3.1
6 info lifecycle padlock@2.3.1~build:linux: padlock@2.3.1
7 verbose lifecycle padlock@2.3.1~build:linux: unsafe-perm in lifecycle true
8 verbose lifecycle padlock@2.3.1~build:linux: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/Workspace/padlock-2.3.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle padlock@2.3.1~build:linux: CWD: /root/Workspace/padlock-2.3.1
10 silly lifecycle padlock@2.3.1~build:linux: Args: [ '-c', 'gulp build --linux --silent' ]
11 silly lifecycle padlock@2.3.1~build:linux: Returned: code: 1  signal: null
12 info lifecycle padlock@2.3.1~build:linux: Failed to exec build:linux script
13 verbose stack Error: padlock@2.3.1 build:linux: `gulp build --linux --silent`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid padlock@2.3.1
15 verbose cwd /root/Workspace/padlock-2.3.1
16 verbose Linux 4.10.0-28-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
Can anyone help?

**Comment by pwasiewicz** [comment]
Have you tried to build without `--silent` option?

**Comment by bbx963872** [comment]
I tried without the --silent option, which shows that "pushd is not fount". Then I solve this problem by 'sudo dpkg-reconfigure dash', and the compile can be completed now. It is a problem caused by the Ubuntu 16.04, not PadLock or Node.js. I also found that the electron based project can not launch in a Gnome remote desktop as in Unity desktop for Ubuntu. Thank you @pwasiewicz . Now Padlock has been complied and  launched without error in Ubuntu 16.04, and i hope my experience can help others.

**Comment by MaKleSoft** [comment]
Thanks, @bbx963872! Appreciate the follow-up!

**Comment by cie6868** [comment]
The error is a result of Ubuntu defaulting to dash when running shell scripts. The `pushd` and `popd` commands are not implemented in dash, but are needed by the bower-install process.

@bbx963872's answer didn't quite work for me on Ubuntu 17.04, but there was a simple workaround.

Just simlink /bin/sh to bash:
`sudo ln -sf bash /bin/sh`

And revert back to `dash` in the same way when you're done.

**Alternatively** you can bypass `pushd` and `popd` using good old `cd`.
Edit the following line on packages.json:
`"bower-install": "pushd app && bower install && popd",`
to
`"bower-install": "cd app && bower install",`
