### ISSUE TITLE
Install in windows server ?

### ISSUE THREAD

**Issue by RomainLongeron** [MaKleSoft/padlock#145]
I am looking to install a password manager on a server to replace my version of keepass which has some compatibility problem with some plugins. Is it possible ? Thank you

**Comment by MaKleSoft** [comment]
It hasn't been tested on Windows Server yet, but why don't you simply download and try? You can find the Windows executable [here](https://github.com/MaKleSoft/padlock/releases/).

**Comment by RomainLongeron** [comment]
I was on a session which does not possess the permissions to execute the
programs. I wanted just already to see if the application corresponded to
my specifications.

Thanks

Cordially


Le 22 nov. 2017 18:23, "Martin Kleinschrodt" <notifications@github.com> a
écrit :
