### ISSUE TITLE
cannot remove fields

### ISSUE THREAD

**Issue by wighawag** [MaKleSoft/padlock#146]
I have added one field but cannot remove it.

I tried setting it to have an empty name and empty content but it still show up on the record list view

Similarly trying to remove the default username or password fields by setting them to be empty does not remove them.

Any plan to allow field removal ?

**Comment by MaKleSoft** [comment]
@wighawag With version 2.3, the delete option has moved to the field 'info' dialog, which can be opened via the `i` icon. I'm assuming you simply didn't see this?

**Comment by wighawag** [comment]
yes, that was it, thanks
