### ISSUE TITLE
Encrypt & store files

### ISSUE THREAD

**Issue by AntoinePrv** [MaKleSoft/padlock#147]
Hello,

First thank you for your great work. I would like to submit a feature request. It would be great if we could add files to our encrypted chest.
I'm not talking about building large encrypted cloud service, but I have a couple of sensible files (such as copy of identity cards) which I feel are part of my identity. I do want them to be secure and backed up for emergencies.

Is that a direction you would consider?

Antoine

**Comment by MaKleSoft** [comment]
Hi Antoine. Encrypting and storing files is a can of worms we'd rather not open at this time. We may revisit the idea at some point down the road but right now the reality is that the demand for such a feature is too low to justify the significant amount of work required to implement it. Thank you for your feedback though!
