### ISSUE TITLE
CMD+H doesn't hide the app on Mac

### ISSUE THREAD

**Issue by moodysalem** [MaKleSoft/padlock#150]
The app appears to be intercepting CMD+H and not allowing me to hide the app via that command. It should only prevent default behavior on key combinations that are recognized

**Comment by MaKleSoft** [comment]
Good catch. Targeting this for v2.5.

**Comment by moodysalem** [comment]
It looks like a bunch of hotkeys are intercepted, including Meta + LEFT/RIGHT/UP on ubuntu and windows. Is that also fixed?

**Comment by MaKleSoft** [comment]
@moodysalem We don't explicitly intercept any of those key bindings but they need to be implemented or at least enabled in electron I think. Unfortunately there is no catch-all fix for this afaik. Can you tell me which key bindings you mean explicitly?
