### ISSUE TITLE
Last setup step is not displayed correctly after resetting the app

### ISSUE THREAD

**Issue by MaKleSoft** [MaKleSoft/padlock#153]
![screen shot 2018-01-11 at 11 46 41](https://user-images.githubusercontent.com/1270940/34828578-26630bf2-f6c5-11e7-8e06-11cd70b86ebf.png)

**Comment by jasonmemez** [comment]
I can confirm this issue.

**Comment by jasonmemez** [comment]
I had to restart the app to get anywhere.
