### ISSUE TITLE
electron-publish issue

### ISSUE THREAD

**Issue by sarada123** [MaKleSoft/padlock#154]
![image](https://user-images.githubusercontent.com/27398044/34864184-0559c8d6-f799-11e7-9e11-9ffc26912c6a.png)
 i am getting this issue after running electron setup

**Comment by sarada123** [comment]
how to overcome

**Comment by MaKleSoft** [comment]
Hi @sarada123. Sorry for the late response! Which operating system are you trying to run this on? Also, what exact commands did you use?

**Comment by sarada123** [comment]
i am working on windows10 and i am using the command electron-buider --platform=win32.
Application is working fine in local.but when i run my exe then only i am getting this error

**Comment by MaKleSoft** [comment]
@sarada123 Instead of using `electron-builder` directly, try
```sh
npm run build:win
```
(See https://github.com/MaKleSoft/padlock#building-for-desktop)

Also, which nodejs version are you using? Padlock requires 8.x or higher.

**Comment by sarada123** [comment]
i am using 8.9.1 version and while trying to run the command i am getting error and my log file is

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:win' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose stack Error: missing script: build:win
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd E:\Samples\ProServeTest
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:win"
8 verbose node v8.9.1
9 verbose npm  v5.5.1
10 error missing script: build:win
11 verbose exit [ 1, true ]

**Comment by MaKleSoft** [comment]
```sh
error missing script: build:win
```
This is weird. What directory are you running the command from?

**Comment by sarada123** [comment]
where my actual code is located, there i am running this. Ex: E:\Samples\ProgramName/ npm run build:win

**Comment by MaKleSoft** [comment]
> where my actual code is located, there i am running this. Ex: E:\Samples\ProgramName/ npm run build:win

Not exactly sure how to parse this. Please make sure you're in the root directory of the project, i.e. the folder that contains `package.json`, `main.js` etc. For example, if you cloned the repository into `E:\Samples\padlock\`:
```sh
cd E:\Samples\padlock\
npm install
npm run build:win
```

Btw, do any other commands work for you? Like `npm run app` for example?

**Comment by sarada123** [comment]
i am running this command in the folder where my package.json and my main.js files exists and "npm run release" is working fine.But it is not doing packaging all the data.

**Comment by MaKleSoft** [comment]
> "npm run release" is working fine

That's weird. There should be no script called `release`. Can you post the contents of your package.json please?

**Comment by sarada123** [comment]
{
  "name": "Sample",
  "version": "1.0.0",
  "description": "My Sample",
  "author": "Sravani",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js",
    "win32": "electron-packager . Sample--platform=win32 --arch=ia32",
    "win64": "electron-packager . Sample--platform=win32 --arch=x64",
    "linux32": "electron-packager .Sample--platform=linux --arch=ia32",
    "linux64": "electron-packager . Sample--platform=linux --arch=x64",
    "osx": "electron-packager . Sample--platform=darwin --arch=x64",
    "build": "electron-packager . --all",
    "release": "npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder"
  },
  "devDependencies": {
    "angular": "^1.5.1",
    "angular-route": "^1.5.1",
    "angular-utils-pagination": "^0.11.0",
    "electron-build": "0.0.3",
    "electron": "^1.7.9",
    "electron-builder": "^19.49.2",
    "electron-packager": "^6.0.2",
    "electron-prebuilt": "^0.36.0",
    "jquery": "^2.2.4",
    "sqlite-sync": "*"
  },
  "build": {
    "appId": "Sample-desktop",
    "asar": "false"
  },
  "dependencies": {
    "angular-animate": "^1.6.8",
    "angular-aria": "^1.6.8",
    "angular-material": "^1.1.5",
    "angular-messages": "^1.6.9",
    "electron-modal": "^1.0.0",
    "electron-open": "^1.0.1",
    "electron-window-manager": "^1.0.4",
    "electron-winstaller": "^2.6.3",
    "excel4node": "^1.3.5",
    "fs-jetpack": "^1.0.0",
    "gulp": "^3.9.1",
    "hashmap": "^2.3.0",
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",
    "sql.js": "*",
    "sqlite-sync": "*",
    "watchjs": "0.0.0",
    "webpack": "^3.10.0",
    "xlsx": "^0.12.0"
  }
}

**Comment by MaKleSoft** [comment]
Not sure how you found this repo but I'm pretty sure you're in the wrong place. Based on your package.json I'm assuming you want to ask this question over at the electron-packager repo: https://github.com/electron-userland/electron-packager

Closing this now.
