### ISSUE TITLE
Upgrade to 2.4.2 from auto download doesn't work

### ISSUE THREAD

**Issue by JC1738** [MaKleSoft/padlock#156]
Downloaded package from site, installed.  Launch says new version available, click download and install, then it never installs.

**Comment by MaKleSoft** [comment]
What version are you trying to update from? There is a known auto-update issue in version 2.3: https://padlock.io/news/v2.4-released/

**Comment by JC1738** [comment]
Yes, it is from 2.3, will upgrade and see if that works for next one after 2.4.  Thanks
