### ISSUE TITLE
Ability to generate one time passwords

### ISSUE THREAD

**Issue by JC1738** [MaKleSoft/padlock#157]
Add the ability to have a type of password that is one-time password.  This will allow the replacement of authenticator or such type apps.  I use this as well as 1password.  It's the big thing 1password does that wish padlock would do (that and use fingerprint/face to unlock iOS app, saw the threads on that request already :)

Thank you,
Jim

**Comment by MaKleSoft** [comment]
@JC1738 Just to be clear, you're looking for a 2fa solution like Google Authenticator? 2FA is a complete different problem domain and clearly out of scope for this project. Or maybe you mean something else? Can you explain some more what this would like exactly?

**Comment by JC1738** [comment]
@MaKleSoft I see, yes, this is the functionality was asking about: https://support.1password.com/one-time-passwords/

**Comment by MaKleSoft** [comment]
I think this feature is a perfect example for the kind of advanced features we wan't to keep out of Padlock for the sake of keeping things simple. Take a look at how this is implemented in 1Password and how complicated the user experience. There are a number of apps that already implement TOTP well enough and even though I can see the advantages of having this bundled in a password manager, I don't think its worth the additional complexity. I'm closing this as "out of scope".

@JC1738 I'd still like to know, though: Is there a specific reason why you don't want to use Google Authenticator or other TOTP apps?

**Comment by JC1738** [comment]
@MaKleSoft Fair enough. It’s the convenience factor of not having to rely on multiple apps for security.  Also if I am on desktop, don’t have to switch to mobile to generate key.  Though there might be a website/desktop app that google provides, need to look.
