### ISSUE TITLE
"Native" version for LINUX

### ISSUE THREAD

**Issue by DOCPROF** [MaKleSoft/padlock#161]
Why not create a "Native" version for LINUX (.deb, .rpm ...)
Because Appimage:
- the system theme does not apply to certain apps,
- impossible to update, must re-download the complete app in appimage.

**Comment by MaKleSoft** [comment]
AppImage is simply the best option for cross-distro deployment at the moment. Publishing and testing different container formats for each distro is simply not feasible at the moment so I'm afraid you're stuck with AppImage for now. The good news is that auto update support for AppImage has landed in [electron-builder](https://github.com/electron-userland/electron-builder) recently so auto updates will be coming with one of the upcoming releases!
