### ISSUE TITLE
Hide all passwords on hover by default

### ISSUE THREAD

**Issue by orentrutner** [MaKleSoft/padlock#162]
With Padlock 2.5.0, you can now individually set each password to either show or stay hidden on hover. But it's set to show by default. With 2.4.2 I had passwords hidden. After upgrading to 2.5.0 they are all shown by default. Changing them one by one is tedious, and there doesn't seem to be a global switch anymore.

Is there, or can there, be a way to hide all passwords in bulk?

**Comment by pwasiewicz** [comment]
The same for me!

**Comment by lewebster** [comment]
Liked the global switch too. Please bring it back.

**Comment by MaKleSoft** [comment]
@orentrutner @pwasiewicz @lewebster Are all your password fields called "password"? Would it be sufficient to hide those by default or do you want to hide all fields?

**Comment by pwasiewicz** [comment]
@MaKleSoft I think hiding fields called "password" only by default is enough for me.

**Comment by orentrutner** [comment]
@MaKleSoft hiding fields exactly named "password" would improve the situation. A couple of additional improvements would be:
- Hiding fields *containing* "password", e.g. "Backup Password"
- Hiding fields containing words from a well known list: "key", "phrase" ("passphrase", "recovery phrase"), "secret", "PIN", "code" (e.g. "MasterCard SecureCode", "Recovery Codes"), "token"

**Comment by MaKleSoft** [comment]
> Hiding fields containing words from a well known list: "key", "phrase" ("passphrase", "recovery phrase"), "secret", "PIN", "code" (e.g. "MasterCard SecureCode", "Recovery Codes"), "token"

That's not a terrible idea. The problem of course is that this only works for english-speaking users.

**Comment by lewebster** [comment]
@MaKleSoft I think hiding the password fields is good enough.

**Comment by pwasiewicz** [comment]
@MaKleSoft  maybe user-definable keywords?

**Comment by MaKleSoft** [comment]
@orentrutner @lewebster @pwasiewicz Quick poll: Are you guys actually using the reveal-on-hover feature? After testing it for a couple of months now I'm not sure anymore if it provides real value in the first place and I'm thinking about removing it completely.

**Comment by forstermatth** [comment]
I'm not using it - if I need to read it, it's easy to go into the view.

**Comment by orentrutner** [comment]
I'm using it on occasion. It's useful to quickly check username fields. It's a nice touch that saves a click. But I can see the argument that it's more trouble than it's worth. I like it, but not to the point of complaining if it goes away.

**Comment by pwasiewicz** [comment]
@MaKleSoft indeed, I am not using it anymore. In 100% cases values are just copied to clipboard.

**Comment by lewebster** [comment]
@MaKleSoft for me it doesn't provide any value. my passwords are all random and at least 22 chars long so revealing them by hovering over doesn't make any sense.

**Comment by sethcasana** [comment]
Aside from any usability issues, the fact that users cannot disable hover previews (or even click previews for that matter) poses a potential security issue. When using your password wallet during a screen share session, in a crowded room, or in any environment when another person is looking at your screen, the ability to disable all fields previews is critical.

**Comment by MaKleSoft** [comment]
As hinted at previously, we decided to remove the reveal-on-hover feature completely in the latest version.
