### ISSUE TITLE
Create a mode system VIEW/EDIT

### ISSUE THREAD

**Issue by beaucoralk** [MaKleSoft/padlock#165]
Hello,

I think it will be great if you make a little icon to lock or not the view.
If the view is locked, record can only be visible and clickable on input to copy content and password, but if the view is not locked, we are in edit mode, and we can edit.
To change the mode from locked to unlocked, the master password is needed.

Did you see what I mean ?

**Comment by MaKleSoft** [comment]
I see what you mean, although I find the concept of a separate mode for viewing and editing somewhat clunky. Having said that, we're still figuring out the best UX for editing/viewing fields and future versions will likely feature a very different way of interacting with fields, possibly a lot closer to what you are describing. Stay tuned!
