### ISSUE TITLE
Invalid URL message displayed incorrectly

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#167]
Additionaly, message about invalid url is displayed (despite url is valid for sure):

![padlock_bug](https://user-images.githubusercontent.com/8725777/37964285-3cb4c184-31c1-11e8-8cac-1db292a8dfbf.jpg)

Disabling Automatic Sync doesn't help.

**Comment by MaKleSoft** [comment]
The custom server setting can't be changed while you're logged in. It's been that way since 2.4 I think. The invalid URL message is a bug. Can you confirm that you can change this settings after logging out?

**Comment by pwasiewicz** [comment]
@MaKleSoft  confirmed. Can change URL after logging out. But message still is displayed.

**Comment by MaKleSoft** [comment]
Fixed. Hope that other than that you're happy with the update so far?

**Comment by pwasiewicz** [comment]
@MaKleSoft  I have created new issue with login code. 

Beside there is only one thing that is a little annoying to me - animation of "Hamburger menu". I think that all users used to animation where width of content is simply decreased to show full-width left sidebar. So current animation of "running content" (I don't event how to call it) looks a little odd to me. But it is my personal opinion :)

![animation](https://user-images.githubusercontent.com/8725777/37965939-21cf2930-31c7-11e8-8240-38c4cf3f39c3.jpg)
