### ISSUE TITLE
Cannot login after logout

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#168]
# Depracted (see edit below)
After logging in on custom server, message appears:
![login](https://user-images.githubusercontent.com/8725777/37965395-3addd630-31c5-11e8-9668-0d6e14aaecf2.jpg)
Email that I have received:

> Hi there!
> 
> You are receiving this email because you requested to pair your Device "xxxxx" with the Padlock Cloud account "patryk.xxxx@xxx.com". To finish the pairing process, please visit the following link:
> 
> https://padlock.xxxx.com/activate/?t=8NHdLvMXZ4npQIj9-vVpzw
> 
> WARNING: This device will gain access to your (encrypted) data! If you did not request to pair this device with your account, DO NOT follow the link above!
> 
> Best,
> The Padlock Team

When clicked URL, device is actived properly. But still - there is no code inside email nor my padlock server site  (padlock.xxxx.com).

I have tried to paste activation code extracted from url (8NHdLvMXZ4npQIj9-vVpzw) and it works but...:

![not allowed](https://user-images.githubusercontent.com/8725777/37965536-b2c0c5e0-31c5-11e8-80f3-e0151434cf7e.jpg)

So - there should be more user-friendly message with login code (non-technical person may not figure out that code can be extracted from url).
If it is going about method "Method Not Allowed" - i think that my proxy server (nginx in my case) is meessing something.

# EDIT:
My padlock-server is out-of-date.
Maybe padlock should send warning when stale version of server-side padlock-server is detected?

**Comment by MaKleSoft** [comment]
Did you update your Padlock Cloud instance to the latest?

**Comment by MaKleSoft** [comment]
@pwasiewicz I'm assuming this is due to your outdated Padlock Cloud instance. Let me know if you encounter any more problems after updating!

**Comment by pwasiewicz** [comment]
@MaKleSoft yeep - see my edit :)

> EDIT:
> My padlock-server is out-of-date.
> Maybe padlock should send warning when stale version of server-side padlock-server is detected?
