### ISSUE TITLE
Unable to setup development environment due to CSP violation

### ISSUE THREAD

**Issue by dploeger** [MaKleSoft/padlock#17]
I cannot start Padlock in my development environment, because Chrome is bothered by the Content-Security-Policy:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' gap:". Either the 'unsafe-inline' keyword, a hash ('sha256-B4XSnYTW0R_oqcAPMdmI9UDnCWideRtvmE1o0XL9Z4c='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

As the CSP in the file is actually

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self' gap:; style-src 'self' 'unsafe-inline'; connect-src https://cloud.padlock.io">
```

this makes sense, because index.html contains inline scripts, which is not allowed.

So shouldn't the inline scripts be either put in a separate file or am I missing something here?

**Comment by MaKleSoft** [comment]
@dploeger You're not missing anything, this is an oversight on my side. Inline scripts are removed from the document during the build process using [Crisper](https://github.com/PolymerLabs/crisper), but this does not happen in 'development mode'. I'll have to figure out a way to disable some of the CSP restrictions during development. For now I suggest simply removing the CSP tag for debugging.

**Comment by dploeger** [comment]
See #18 for a suggestion. :)
