### ISSUE TITLE
New Logo For Padlock

### ISSUE THREAD

**Issue by mirzazulfan** [MaKleSoft/padlock#172]
Hi, I designed a logo for your project. If you like it, you can use it. I will send you files. free for your project. Best Regard.
![padlock](https://user-images.githubusercontent.com/36124339/38821997-5cff26f8-41cc-11e8-87c3-2a14e4c994fb.png)

**Comment by MaKleSoft** [comment]
@mirzazulfan Thanks for your contribution! At this point we're not really looking for a new logo though.
