### ISSUE TITLE
Autofocus Main password field!

### ISSUE THREAD

**Issue by forstermatth** [MaKleSoft/padlock#173]
Now that you've given me the ability to just type without clicking the search box, I keep trying to use the same flow to type in my master password!

It'd be awesome if we could autofocus the master password input when we switch to the padlock app.

**Comment by MaKleSoft** [comment]
The desktop app already automatically focuses the password input when launched initially but you're right, the same behaviour make sense when receiving focus after being in the background. Consider it done!
