### ISSUE TITLE
Own padlock-cloud server - trial?

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#180]
I have configured **own, newest padlock-cloud server**. After logging, my account tab shows lots of messages:

![trials](https://user-images.githubusercontent.com/8725777/39642260-78637abc-4fd1-11e8-9544-2ab4cbf2ca43.jpg)

**I am not able to synchronize with own padlock-cloud server**. Is this feature paid? If yes, none of buttons  work (activating, upgrading account). If no, these messages should not be visible and padlock should allow me to sync passwords.

**Comment by forstermatth** [comment]
To piggyback onto this issue - I am also having problems adding _new devices_ to my current custom server, as it always says that the URL is invalid, although it is not.

**Comment by pwasiewicz** [comment]
@forstermatth I had the same problem. Reffer: https://github.com/MaKleSoft/padlock/issues/167
Upgrading padlock helped.

**Comment by MaKleSoft** [comment]
@pwasiewicz This is a bug with in v2.7.0 that has since been fixed in master. Fix will be released in v2.7.1

**Comment by forstermatth** [comment]
@pwasiewicz Upgrading padlock-cloud or client? I believe I was using v2.7 on the client - it just said invalid URL. I'll attempt again when I have access to it and make sure it was the most recent.
