### ISSUE TITLE
Nice Update On Mobile!!

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#183]
Hey, awesome update on mobile!! I'm glad to see you still working on this project more and more 👊

**Comment by MaKleSoft** [comment]
Glad you like it! Our goal was to improve user experience in general but mobile certainly is where we are seeing the biggest impact. What changes did you like specifically and why?

Btw, while we like getting our bellies rubbed, the issues section is not necessarily the appropriate platform to communicate your praise 😄If you'd like to help spread the word, we always appreciate positive reviews in the iOS or Android app store! Or if you just want to let us know we're doing a good job, feel free to shoot us an email any time!
