### ISSUE TITLE
Problem with syncing record changes in v0.10.0

### ISSUE THREAD

**Issue by inikolic** [MaKleSoft/padlock#22]
After updating to v0.10.0 Padlock Cloud synchronization works only when new records are created.
Deleting and updating records (adding/removing/updating fields) actions are not synchronized.
This problem is manifesting both ways on following setup:
Chrome app on PC (Win8.1, Chrome 45.0.2454.101) with iPhone app (iOS 9.0.2).

**Comment by MaKleSoft** [comment]
@inikolic Good catch! Don't know how this did not show up during beta testing.

**Comment by inikolic** [comment]
If I have a penny for every time I said that :-D
