### ISSUE TITLE
Records are not deleted from other devices on synchronisation

### ISSUE THREAD

**Issue by s4astliv** [MaKleSoft/padlock#25]
Noticed an issue on synchronisation. When I add a new record, it instantly appears on other devices. When I delete it, it disappears only from the device that it was deleted from. It is still present on other devices, even when running manual synchronisation.

**Comment by MaKleSoft** [comment]
@s4astliv This has already been reported in https://github.com/MaKleSoft/padlock/issues/22 and fixed with https://github.com/MaKleSoft/padlock/pull/23. Thanks for reporting this though!
