### ISSUE TITLE
Could someone create a Synology package?

### ISSUE THREAD

**Issue by bentheone** [MaKleSoft/padlock#31]
I´m not big with linux but I would love to see this password manager on my Synology DS Server.

**Comment by MaKleSoft** [comment]
@bentheone I'm assuming you're talking about running a Padlock Cloud instance on your server? If so, that issue would belong in https://github.com/MaKleSoft/padlock-cloud/issues

**Comment by bentheone** [comment]
Thank you, I created it there.
