### ISSUE TITLE
Plans for collaborative features?

### ISSUE THREAD

**Issue by pirogoeth** [MaKleSoft/padlock#33]
Are there any plans for adding a sort of collaborative feature in the future? Padlock looks absolutely excellent, but I would like to use it in a somewhat "enterprise" environment and be able to share secrets with a user or group of users.

**Comment by MaKleSoft** [comment]
@pirogoeth Yes, this is definitely part of the long-term vision of the project. Implementing this is also far from trivial though, so it'll probably be a while...

**Comment by pirogoeth** [comment]
@MaKleSoft Understandable. I was looking through the code to see how encryption was done, hoping for a sort of PKI. Using (and storing) GPG-style pubkeys for each user would make collaboration simple, but that doesn't really fit in this situation :(

**Comment by MaKleSoft** [comment]
@pirogoeth Implementing collaborative features will certainly require some form of asymmetric encryption but I don't see any 'easy' way of doing it. The challenge here is that the store of any individual user is meant to be decrypt-able only with the knowledge of their individual master password. I'm thinking about having users exchange "change sets" for shared records, which are encrypted using the other users public key and then shared either peer-to-peer or through a public service like Padlock Cloud. This sounds relatively simple at first, but it introduces the problem of how to do the key exchange / authentication. If you have any suggestions on how to design a protocol for this, I'd certainly be interested in hearing them.

**Comment by pirogoeth** [comment]
@MaKleSoft Yeah, I've been throwing some ideas around in my head for the past day or so, but it would be a lot of change in how the system currently works, I think. 

From what I could tell, all encryption is done using AES directly on the data and the encrypted data is pushed up to the cloud instance when syncing, yeah?

What I'm thinking is you have the client generate a pub/priv key-pair and enforce private key encryption with a master password (as opposed to leaving it bare). Encrypted data would still be synced up to the cloud instance, but you'd also send up the public key associated with account, simply to make sure it is there/up-to-date. 

The sharing would take place on the client-side, as many of the padlock operations currently do: the secret owner wants to share the secret with another user, so the client-side pulls the other user's public key, requests that the secret be decrypted on the client side, and then re-encrypts the secret using the target user's public key. When this happens, you'd have to store some metadata on the cloud that essentially stores the facts that:
 - This secret is shared by <this user>
 - This secret is shared to <these users...>
 - This CRL is used to determine who/which public keys still have access to decrypt the secret(ish..)
 - This is the latest hash of the secret
 - This is the latest hash of the CRL

When pulling on the "remote" side, the client would verify the secret's status, make sure their cert is not on the CRL (and if it is, the remote side's secret gets destroyed, locally and on the cloud), and then allows the user to decrypt their "share" of the secret.

I know there may be some glaring problems (and maybe writing errors) with this, but I'm still drinking my morning coffee so I'm not all there yet. 

Anyway, thoughts?

**Comment by MaKleSoft** [comment]
@pirogoeth This is conceptually close to what I was thinking. Of course this process would have to happen every time a shared record is updated. This is why I was talking about "changesets". Like I mentioned before, one of the major challenges in this scenario is the exchange of public keys. The simplest solution would be to simply store them on a public server like Padlock Cloud but that would make the protocol vulnerable to eavesdropping attacks by simply replacing the public key on the server with one generated by an attacker (in the case of a malicious server administrator this would be trivial). In short, distributing public keys through a public channel is simply not a viable option so we would have to find a way to exchange private keys directly between clients.

**Comment by pirogoeth** [comment]
@MaKleSoft Maybe this is a case where some "identity proofing" mechanism (as is done in [Keybase](https://keybase.io/)) would be extremely useful. 

If the secret can only be updated by the original owner, the secret and it's original metadata are encrypted with the original owner's private key before pushing, and the owner's public key is fingerprinted, hashed, etc. and pushed read-only to the cloud server, I believe we can bypass most of that problem. 

If we make public keys that are uploaded to the server completely immutable and concretely linked with a "identification card", then we shouldn't need to worry about a public key being replaced on the server. Of course, we'd have to hold hashes or fingerprints of public keys in the database to make sure they aren't changed by the server owner. We could also have a sort of handshake implemented in the protocol which ensures that the user's key-pair has not been changed...

Realistically, distributing the public keys through the cloud channel is a relatively safe option, since a private key (and a private key passphrase..) will still be required for decryption. As long as the encryption algorithm is strong and is resistant to many of the common attacks, we should be okay to handle keys and crypted secrets this way.

Of course, if we did decide to distribute public keys directly between clients, then we could use something like DHT or some other peer discovery technology to do the transfer.

**Comment by MaKleSoft** [comment]
> If we make public keys that are uploaded to the server completely immutable and concretely linked with a "identification card", then we shouldn't need to worry about a public key being replaced on the server.

Of course, there is no such thing as truly 'immutable'. If a malicious actor obtains control of the server, any safeguards in the application logic can easily be circumvented. My issue with this is that it places too much responsibility on the server administrator. My philosophy is to always work under the assumption that the cloud server is already compromised. Even under that circumstance, it should be impossible for an attacker (including malicious server administrators) to

1. Read any sensitive user data stored on the server
2. Trick a user into transmitting data in a way that makes it accessible to the attacker
3. Trick a user into accepting unintentional changes to their data

> Of course, we'd have to hold hashes or fingerprints of public keys in the database to make sure they aren't changed by the server owner.

I'm assuming you mean storing these things locally on the client? Yes, once a key exchange has taken place, public keys can be cached in the users local database, which is encrypted with the users master password and can therefore be considered 'immutable' for all intents and purposes. However, this leaves the problem of the initial key exchange. What guarantees you that at the point you share a record with a new user (which is where the initial key exchange would take place), the corresponding public key has not already been replaced by an attacker? In that case, checking that a key pair hasn't changed is, of course, not helpful.

> Realistically, distributing the public keys through the cloud channel is a relatively safe option, since a private key (and a private key passphrase..) will still be required for decryption.

Again, the key problem here is to make sure that a clients uses the right public key for encryption when publishing updates. If at some point a client has been tricked into accepting a public key controlled by an attacker, any updates will be easily decrypt-able by the attacker.

I'm not yet discarding the possibility of completely handling this over the cloud, but it's clearly not a trivial problem and should be approached with a lot of caution.

**Comment by pirogoeth** [comment]
Yeah, I definitely agree. You brought up some very good points which I guess I hadn't considered in-depth.

Probably the most secure way to implement this would be to have it offloaded all to the client-side with some sort of peer discovery for secret sharing. That way, you don't have to worry about the possibility of a compromised master server, malicious server admin, etc. 

You've given me a lot of stuff to sit and think on, so I'm gonna try and process for a while and see what I come up with.

**Comment by JosefJezek** [comment]
Check out the Mitro

https://github.com/mitro-co/mitro
https://github.com/mitro-co/mitro/blob/master/PasswordManagerDesign.pdf
http://fc13.ifca.ai/proc/4-2.pdf

Mitro have secret sharing feature...

**Comment by eduardbosch** [comment]
This feature will be REALLY useful! I was looking for that and I've found this issue asking about managing different keys with different groups of people.

I hope this is something that padlock can implement in a future. It will help a lot sharing groups of credentials with different people.

**Comment by MaKleSoft** [comment]
This is still very much on our radar but too far in the future to keep it in the issues section so I'm closing this for now.
