### ISSUE TITLE
Option to disable or greatly speed up animation

### ISSUE THREAD

**Issue by moodysalem** [MaKleSoft/padlock#35]
It's nice to look at at first, but if you're using the app frequently they slow you down quite a bit

**Comment by MaKleSoft** [comment]
May I ask how many records you have? Also, which device are you using? I've put a lot of effort into making the animations as smooth as possible and the app seems to be running pretty smoothly on all the devices that I'm testing on.

**Comment by moodysalem** [comment]
I haven't actually had any performance issues, it's just that I prefer no animations since I've gotten used to the screens and I know where things will be when the animations end.

**Comment by MaKleSoft** [comment]
Ah, thanks for the clarification. yeah, a 'simple' mode without animations may have value for some users. I'll think about it. Thanks for the suggestion!

**Comment by moodysalem** [comment]
I had performance issues when using this on a 4k monitor on kubuntu with the app full screen

**Comment by MaKleSoft** [comment]
Closing this for now, but something we might revisit later
