### ISSUE TITLE
Feature request: Ability to show/hide master pass on unlock

### ISSUE THREAD

**Issue by danblah** [MaKleSoft/padlock#36]
Heya good folks developing padlock! Thanks for making this tool :) With self interest in mind, I'm about to post a hand full of features that are keeping me from adopting padlock over keypass full time.

**Comment by MaKleSoft** [comment]
Hey @danblah! Thanks for the suggestion! Sounds like a reasonable request. I'll consider it!

**Comment by MaKleSoft** [comment]
-> backlog. Thanks again for the suggestion!
