### ISSUE TITLE
Feature request: allow an unlock period for both mobile and desktop app

### ISSUE THREAD

**Issue by danblah** [MaKleSoft/padlock#37]
The ability to stay unlocked for a few minutes to all day for both mobile and desktop

**Comment by MaKleSoft** [comment]
@danblah The auto-locking behavior will definitely be revamped in one of the upcoming releases. I already have this on my to-do list but I'll leave this issue here for reference.

**Comment by danblah** [comment]
Brilliant, looking forward to it!

**Comment by MaKleSoft** [comment]
This has already been implemented and will be in the next release. Closing this issue.
