### ISSUE TITLE
Port to native app shell around webapp

### ISSUE THREAD

**Issue by moodysalem** [MaKleSoft/padlock#40]
The chrome app has tab switching issues that make it a pain to use (and it seems like it will for the foreseeable future)
https://bugs.chromium.org/p/chromium/issues/detail?id=278408

Would like to suggest moving to something like electron
http://electron.atom.io/

**Comment by rangeroob** [comment]
Personally I'd love to have padlock introduce a standalone app separate from the browser so we aren't forced to open a browser every time we want to open padlock on desktop

**Comment by MaKleSoft** [comment]
This is definitely coming, probably sooner rather than later. Thanks for the feedback!

**Comment by moodysalem** [comment]
@MaKleSoft Can you document in the padlock-cloud repository the public service API? I'd like to play around with electron and this would be a fun opportunity

**Comment by MaKleSoft** [comment]
@moodysalem Yeah, I know documenting the service api is way overdue. I'll get on it asap. In the meantime, you should be able to figure out most of it by looking at https://github.com/MaKleSoft/padlock/blob/master/src/CloudSource.js. Note that this is for the Padlock Cloud Api v1, as opposed to v0, which is currently deployed at `cloud.padlock.io`. If you want to test against the new api, you can either spin up you own instance or use `cloud-dev.padlock.io`. If you need help with any of that, let me know!

Btw, it looks like Cordova is gradually adding support for desktop platforms. Ubuntu and Windows are already officially supported and it looks like OSX is not far off. It would be nice to have one solution for x-platform deployment but exploring other options like Electron or nw.js is definitely worth a shot, too. So yeah, please have at it! I'm excited to see what you come up with! If you need any assistance, please don't hesitate to contact me.

**Comment by gedw99** [comment]
@moodysalem I did not knwo Cordova can also handle Desktops. 
I have been trying to work out if it uses Chromium on all desktops, like Electron does ?
If you happen to know it would help me.

The reason is because of my worries about cross browsers bugs. With Electron its one browser (Chromium), and so it lowers the potential for bugs.

**Comment by MaKleSoft** [comment]
@gedw99 That's a good question. I would assume that by default, Cordova uses the web view that comes with the operating system, meaning IE on windows, Safari on OSX etc. However, there is the [Crosswalk](https://crosswalk-project.org) project, which allows to bundle the Chromium runtime with the app. We're already using crosswalk for android via the [cordova plugin](https://www.npmjs.com/package/cordova-plugin-crosswalk-webview/) but it doesn't look like the plugin supports any platforms other than android right now. As of now, the Padlock app has been tested on both Chromium and Safari (on iOS there is no way around WebKit right now). Pretty sure Cordova for Linux uses Chromium so the only thing that I'm worried about is Windows.

**Comment by MaKleSoft** [comment]
Working full-steam on this and it looks like v1.2 will be available as an electron-wrapped native app for all major desktop platforms. In fact, there is an early alpha version for mac available now: https://github.com/MaKleSoft/padlock/releases/tag/v1.2.0-alpha.2

Closing this now.
