### ISSUE TITLE
Word error: loose/lose

### ISSUE THREAD

**Issue by AdamZ** [MaKleSoft/padlock#41]
[This line](https://github.com/MaKleSoft/padlock/blob/1c7c5e04f7937d505a43613fc456f4eae6ed850e/src/components/cloud-view/cloud-view.html#L21) contains a word/spelling error. "Loose" should be "lose".

**Comment by MaKleSoft** [comment]
Thanks! Fixed: b90513d9a7c8191c6e37d4ababd465bbec47c1ca
