### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#46]
Not that important, but would be nice

**Comment by MaKleSoft** [comment]
@eorroe Can you explain in more detail what exactly you mean by 'fuzzy search'?

**Comment by eorroe** [comment]
I'm trying to find a good online example, but depending on what text/code editor your use. I'm sure most  implement it, but take sublime for example when you search and make a typo it still finds the result:

- facebook
- fbook
- mbook

if you search "fbok" both **fbook** and **facebook** show because "fbok" are in both strings

**Comment by MaKleSoft** [comment]
-> backlog. Just did some research and there seem to be some decent libraries for this. Not high-priority though
