### ISSUE TITLE
Have you read this?

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#49]
Chrome is killing chrome apps [source](http://www.technobuffalo.com/2016/08/21/google-were-killing-chrome-apps-in-2018-sorry/)

**Comment by MaKleSoft** [comment]
Yeah, I was aware of this, but thanks for pointing it out. We were planning to deploy the app in native shells for the various platforms anyway, I guess this just means we'll up the priority a bit. See also https://github.com/MaKleSoft/padlock/issues/40 for some discussion
