### ISSUE TITLE
How to import additional fields using .csv?

### ISSUE THREAD

**Issue by steveharman** [MaKleSoft/padlock#51]
I've managed to export all the data (as .csv) from my existing password manager app with a view to moving to Padlock.  Along with the usual Username, Password & URL, most of my existing records have "**Notes**" along with Name, Category, Url, Username, and Password 

I'd like to get *all* my existing data into Padlock including the notes - can I simply create a .csv containing Name, Category, Url, Username, Password, **Notes** - paste that into Padlock as part of the import process and expect Padlock to create a 'Notes' field?

Thanks,

**Comment by MaKleSoft** [comment]
Yes, that should work just fine! Padlock should be able to recognize the
additional field and automatically create it when importing. May I ask
which password manager you are exporting your data from?

Let me know if you run into any problems!

**Comment by steveharman** [comment]
Thanks I’ll give it a try.   My data is coming from aWallet (http://www.awallet.org/)  Which I have no problem with whatsoever, I simply like the look of Padlock so wanted to give it a try.

Steve

**Comment by MaKleSoft** [comment]
@steveharman Closing this issue now. How did this work out for you?
