### ISSUE TITLE
Broken link for Chrome Web Store on padlock.io

### ISSUE THREAD

**Issue by topless** [MaKleSoft/padlock#52]
In padlock.io in the section **How can I use it?** the link to Chrome Web Store instead of pointing to  https://chrome.google.com/webstore/detail/padlock/npkoefjfcjbknoeadfkbcdpbapaamcif

it points to 

https://chrome.google.com/webstore/detail/padlock/npkoefjfcjbknoeadf

which returns a `404`

**Comment by MaKleSoft** [comment]
@topless So it does! Thanks for pointing it out! I've fixed the link. Btw, the code for the padlock.io website is also on github (https://github.com/maklesoft/padlock.io/) so next time you find any problem with the website feel free to report it there directly or maybe even fix it and create a PR yourself!

**Comment by topless** [comment]
I looked for it briefly and didn't find it! Thanks for pointing out, I will for sure!
