### ISSUE TITLE
Feature Request: Sort by Section Name

### ISSUE THREAD

**Issue by edwinbradford** [MaKleSoft/padlock#53]
The websites are listed in alphabetical  order. Would it be possible to add the option to list by section? That would make sections more useful than they are now as currently they are more like tags. I ask because this is a feature of LastPass and SafeInCloud from which I've switched. Also if the section and alphabetical headers were collapsible I believe it would speed up the UX by reducing the amount of scrolling required.

I hope that's helpful. I'm currently running Padlock Cloud on two PCs and Android with no issues.

**Comment by MaKleSoft** [comment]
Hi @edwinbradford! I got this exact same feature request (sorting by category) in an email a while ago. Here is what I answered back then:

> That is a great idea! So great in fact that we had exactly this feature in a previous version. Why did we remove it? Well, as you might know our philosophy is to create a user experience that is as simple as possible by limiting the features of the app to only the most essential. Sorting by category made sense for some users, but we noticed that the vast majority of users where never using it! By removing the feature, we were able to clean up some of the UI and - more importantly - optimise the search feature to be much faster than before. Btw, did you know that you can filter records by category? Simply enter the category name into the search input at the top! I personally find this much more efficient than browsing manually through records, no matter how they are sorted. What do you think?

For me, clicking on the search field (or hitting `ctrl + f` if your on a desktop`) and hacking in the first few characters of the thing I'm looking for is usually much faster than scrolling through the list anyway, regardless of how the list is sorted. Collapsible headers are a fine idea, too, but pretty much the same argument applies here. I encourage you to experiment with the search feature and see how quickly you can find things without any scrolling at all! Try it for a while, then let me know what you think!

**Comment by edwinbradford** [comment]
Hi MaKleSoft, That's completely understandable. I'm sorry I didn't see the previous request, that was my error. I'm sure you're right, I'm switching from another app so I'm used to doing things the other way but I'll try your suggestions and let you know if I can't adapt. Thanks for the great app and for being so responsive to feedback.
