### ISSUE TITLE
Support for self-signed certificates

### ISSUE THREAD

**Issue by peterloron** [MaKleSoft/padlock#54]
Please consider adding support for self-signed certificates to the client.

**Comment by MaKleSoft** [comment]
Blindly trusting self-signed certificates kind of defeats the purpose of using https in the first place, as this makes is almost trivial to implement a man-in-the-middle-attack, rendering the encryption basically useless. The only way to safely use self-signed certificates would be to also implemented some sort of certificate pinning, which is not trivial to do cross-platform. For now, I recommend simply getting a certificate from a trusted CA. With the rise of [letsencrypt](https://letsencrypt.org/) this has become fairly easy (and free) so there is really no good reason not to do it these days. Having said that, having a way to safely use self-signed certificates would certainly be a nice to have, and possibly something that we'll consider for the future.

**Comment by MaKleSoft** [comment]
P.S.: The [Cordova App Security Guide](https://cordova.apache.org/docs/en/latest/guide/appdev/security/index.html) has some useful information on this topic.
