### ISSUE TITLE
Where does Padlock store passwords (locally)?

### ISSUE THREAD

**Issue by maxalbert** [MaKleSoft/padlock#55]
This is mostly a documentation issue, but I couldn't find any information about where Padlock stores passwords (when using local storage, which AFAIU is the default?). Is this configurable somehow?

Apologies if I missed this - I only just discovered Padlock and haven't had much time exploring it in detail.

Many thanks for making Padlock available, and for staying true to the clear objective of keeping it minimalist and intuitive. :)

**Comment by MaKleSoft** [comment]
You are correct that Padlock currently uses the `localStorage` feature of the underlying webview. Were the data is ultimately stored on disc is different for each platform and not configurable. This definitely needs to be more transparent. We'll probably soon switch to using the file system directly where possible which will give us (and the user) more control over where the data is stored.

**Comment by kadaj** [comment]
The localstorage has [size limitation](http://stackoverflow.com/a/35864755/235273) depending upon the browser the cordova app uses. Please save it to filesystem. Also please provide option to save the exported data to filesystem instead of clipboard. I think the clipboard has some restriction on the amount of bytes it can copy. The encrypted data can get huge if I have a lot of data stored in padlock.

**Comment by MaKleSoft** [comment]
@kadaj You're right, although we've never had reports of cases where the size limit of either was not sufficient. I think it is reasonable to assume a certain upper bound in the order of magnitude of the number of passwords a person would ever reasonably want to store (E.g. I think it's safe to assume that nobody will ever reach the 100k mark, even 10k seems unlikely) but for the sake of robustness, we're definitely planning on migrating to storing data on the filesystem directly.

**Comment by kadaj** [comment]
@MaKleSoft Will you provide an export option to the file system instead of clipboard?

**Comment by MaKleSoft** [comment]
@kadaj Absolutely! That was the plan from the start, really.
