### ISSUE TITLE
Use asymmetric encryption

### ISSUE THREAD

**Issue by moodysalem** [MaKleSoft/padlock#57]
IDK if this is a real issue or not, but I was thinking about it this morning

It seems like the architecture is that the DB file is symmetrically encrypted using the passphrase I choose and stored on the server to be synchronized with other devices

That means if someone gets ahold of my database file somehow (e.g. back end server breach) they could relatively easily brute force or dictionary attack passwords on the file unless my passphrase was very complicated (and I doubt most people have complicated passphrases)

Seems like padlock should be using public key encryption where each machine has its own key pair and the key pair has a passphrase-allows you to use different keyphrases on different machines as well. The only limitation of that approach is that a machine with access to the file has to be used to approve adding another device, because it would have to decrypt the file and re-encrypt with a new set of public keys

LMK if I'm totally off base here (I'm hoping that I am)

**Comment by MaKleSoft** [comment]
Brute-force and dictionary attacks are real concerns but there are steps we are taking to mitigate the risks. Basically it comes down to using the right method for key derivation. We're using [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2), which uses a method called [key stretching](https://en.wikipedia.org/wiki/Key_stretching) to make these kind of attacks harder. Of course, the reality is that an attacker with sufficient resources might still be able to break the encryption within a finite amount of time but using the methods mentioned above, we can make it uneconomical for an attacker to even try (i.e. it would take years and millions of dollars to break the encryption, even with a moderately strong password). Of course that means making sure users are using strong passwords is a big concern, but that is what the strength-meter and the warning for weak passwords at the getting started screen is for ;)

Aside from the fact that asymmetric encryption is not feasible for large amounts of data I don't see how your approach would make the encryption any more robust. Can you explain, for example, how it would protect against brute-force attacks?

**Comment by moodysalem** [comment]
Hmm-I'd never heard of key stretching-that eases my concern a bit depending on how expensive it is to test a single passphrase against a DB file.

If you are using public key cryptography, the attacker would need both the DB file AND a private key from one of the connected devices to attempt to decrypt the file. It is completely impractical to generate a private key from the public keys for which the DB file is encrypted, and the server has no knowledge of the private keys. So a device has to be compromised in order for the DB files to be brute forced/dictionary attacked. How come you say it's not feasible to encrypt large amounts of data with public key encryption?

**Comment by moodysalem** [comment]
PS I think iCloud keychain does something similar just based on the fact that it requires me to approve additional devices from other machines

**Comment by MaKleSoft** [comment]
About why asymmetric crypto is not feasible for large amounts of data: http://crypto.stackexchange.com/a/5790

**Comment by moodysalem** [comment]
It seems that's more of a performance/storage space concern-I wouldn't have any issue with waiting a few seconds for my db file to synchronize/decrypt/encrypt since it's not real time. I'm not sure what the average file size is for people's databases though. 

If necessary for performance though it's possible to use the suggested workaround of using asymmetric encryption to get at a long symmetric encryption key. The server would just have to store both the asymmetrically encrypted key and the symmetrically encrypted db file

Seems like a lot of work to change, but IMO it would be nice to know my data is totally safe from attack in case of a server breach

**Comment by MaKleSoft** [comment]
> It seems that's more of a performance/storage space concern-I wouldn't have any issue with waiting a few seconds for my db file to synchronize/decrypt/encrypt since it's not real time.

I don't know how much longer it would take to encrypt the data with, say, rsa, but we're definitely talking about orders of magnitude here. It's quite possible that "a few seconds" won't be enough.

Also, if the data is encrypted with a device-specific public key and then stored on the server, how are other devices supposed to decrypt the data? Of course if every device knew the public key of every other device, it could upload an specifically encrypted version for each device but that leaves you with the fundamental problem of how to safely exchange public keys. And by the way, what makes you think that asymmetric crypto is not susceptible to brute-force attacks?

**Comment by moodysalem** [comment]
> I don't know how much longer it would take to encrypt the data with, say, rsa, but we're definitely talking about orders of magnitude here. It's quite possible that "a few seconds" won't be enough.

I was basing that guesstimate on the fact that symmetric algorithms were estimated to do 2000MB/s in that stackoverflow post, and asymmetric crypto being 5000 times slower- somewhere in the 0.5MB/s range-and my guess of my database file not being any larger than a MB (all I'm storing is textual data-but I'm not positive what other metadata is in that file)

> Also, if the data is encrypted with a device-specific public key and then stored on the server, how are other devices supposed to decrypt the data? 

It's encrypted with multiple device-specific public keys as recipients, so anyone with any of the corresponding device private keys can decrypt the file.

In order to add a device, a machine that has a working private key would have to decrypt the file and then re-encrypt it with the additional public key in addition to the existing public keys. AFAIK with GPG the encrypted file contains information about which public keys it was encrypted for. It should always be safe to exchange public keys-you could store the active public keys on the server and information about whether they have been incorporated into the DB file, so that a client can when it needs to authorize another device

Asymmetric crypto is technically susceptible to brute-force attacks, but a typical private key size is 2048 bits

**Comment by MaKleSoft** [comment]
> Asymmetric crypto is technically susceptible to brute-force attacks, but a typical private key size is 2048 bits

I'm sure you know this, but due to the mathematical correlation between public and private key, a 2048 bit rsa key is roughly equivalent in strength to a (completely random) 128 bit aes key and using a larger key would likely not be practical due to performance concerns.

If I understand you correctly, your argument is that data encrypted using your technique would be less susceptible to key-guessing attacks due to a larger key space (because the 256 symmetric encryption keys are derived from the significantly smaller subset of passwords that can be handled by humans) but this is exactly what we're trying to mitigate through key stretching.

Its hard to say without running the numbers, but its quite possible that the encryption scheme you're suggesting would actually be **easier** to break than what we have now. More importantly though, it is significantly more **complicated** and arguably far from common practice. Don't get me wrong - I highly appreciate your input but if I've learned one thing about cryptography, its that its usually best to stick to simple, battle tested patterns and common practice where possible. Crypto is hard enough to get right as it is without trying to come up with new solutions to already solved problems.

Btw, it's worth pointing that out that I do see use cases for public key crypto in the future, specifically when it comes to sharing records between multiple accounts but for now I think it's best to stick with what we have.

**Comment by moodysalem** [comment]
> I'm sure you know this, but due to the mathematical correlation between public and private key, a 2048 bit rsa key is roughly equivalent in strength to a (completely random) 128 bit aes key and using a larger key would likely not be practical due to performance concerns.

Actually I didn't! Still, the bits are random so you don't have to worry about dictionary attacks. 

If an attacker got a hold of all the DB files, I would imagine the attacker would run a dictionary of common passwords through the key stretching algorithm, and then try each of the stretched keys against each of the databases. If you're doing key stretching in addition to salting, that would be less of a concern-but I didn't see that was mentioned.


> If I understand you correctly, your argument is that data encrypted using your technique would be less susceptible to key-guessing attacks due to a larger key space (because the 256 symmetric encryption keys are derived from the significantly smaller subset of passwords that can be handled by humans) but this is exactly what we're trying to mitigate through key stretching.

It's less susceptible to key guessing because the key isn't determined by the user. The key is generated by the computer, and the user just picks a passcode on the device to unlock the key. The key is never shared with the server, so the attacker has to guess the longer private key instead of the user-selected passphrase. I can't imagine a scenario in which trying to guess a generated private key is easier to do than trying to guess a user-selected passphrase.

I do think it's a lot more complicated-but I also think this is what Apple does for iCloud keychain, so it's pretty safe to say it's the right way to share credentials between devices. See the iCloud keychain section here: https://support.apple.com/en-us/HT202303

**Comment by MaKleSoft** [comment]
> Still, the bits are random so you don't have to worry about dictionary attacks.

They aren't though. Key pairs are generated by solving a hard math problem the **parameters** of which are chose at random. This means that a asymmetric key of 2048 bits has **significantly** less entropy than a key of the same size in which every bit is chosen completely at random. It's true that dictionary attacks are not applicable to asymmetric key pairs but there are other techniques that are significantly more efficient than randomly guessing every single bit.

Anyway, I've heard your argument but I my decision remains to not change anything about the encryption scheme right now. I hope you don't mind if I close this issue now.

**Comment by MaKleSoft** [comment]
I forgot to mention that the current encryption scheme was reviewed by experts during a recent penetration test which perhaps will further ease your concerns. The report will be published soon.

**Comment by moodysalem** [comment]
> They aren't though. Key pairs are generated by solving a hard math problem the parameters of which are chose at random. This means that a asymmetric key of 2048 bits has significantly less entropy than a key of the same size in which every bit is chosen completely at random. 
I just meant at least there are 128 bits of randomness, vs. a user chosen passphrase (I think you should try and see how many db files you can unlock with 'password')

> It's true that dictionary attacks are not applicable to asymmetric key pairs but there are other techniques that are significantly more efficient than randomly guessing every single bit.
If someone figured out how to crack a modern public key crypto algorithm in a feasible amount of time, there would be a LOT of other valuable targets

> Anyway, I've heard your argument but I my decision remains to not change anything about the encryption scheme right now. I hope you don't mind if I close this issue now.
No worries, I appreciate the discussion. Thanks
