### ISSUE TITLE
Shortcuts inside input fields

### ISSUE THREAD

**Issue by eduardbosch** [MaKleSoft/padlock#60]
Hi,

I've found that shortcuts does not work on mac app while inside input fields.

If you try cmd+a (to select all), cmd+c / cmd+v (to copy / paste), none of these works.

It's a little bit annoying when you want to select all text to reenter a wrong password for example.

Copy and paste features are also really annoying when creating new entries (I know that copy is still working while non editing an input field).

Thanks for this great app 👍

**Comment by MaKleSoft** [comment]
Good catch, thanks! Fixed: https://github.com/MaKleSoft/padlock/commit/4ac3e92512d36f5f090f51da42c4de1e73d3477e
