### ISSUE TITLE
Entries aren't alphabetized and displayed correctly

### ISSUE THREAD

**Issue by bkjohnson** [MaKleSoft/padlock#62]
I'm using Linux so that might be part of the problem, but I cloned and installed the repo and wanted to test some things out.  I added a few passwords and saw unexpected behavior:

![image](https://cloud.githubusercontent.com/assets/2008881/20607957/832d5b3a-b242-11e6-84b2-b0a90446e959.png)

I would've expected the Slack entry to be under its own "S" heading.

This issue led me to try PadLock in another browser, where I discovered issue #61

**Comment by MaKleSoft** [comment]
This might be a known issue where items sometimes appear in the wrong section right after they are added. Does the problem persist if you reload the app?

**Comment by MaKleSoft** [comment]
Fixed in 2.0.0

**Comment by bkjohnson** [comment]
Sorry for not getting back around to this, I was busy at the time.  I'll try to check this project out again in the near future.
