### ISSUE TITLE
When padlock auto timeouts and locks, the data entered is not saved under Android

### ISSUE THREAD

**Issue by kadaj** [MaKleSoft/padlock#63]
Steps: I have created an entry and I tap the back button, it is saved. Now I am editing the entry. I add some texts, then the phone is idle and it locks the phone, and the padlock. I unlock the phone and the padlock, but the entered text is not saved since I did not tap the back button manually.

Expected: When padlock auto locks, save the current entry if it is not saved.

**Comment by MaKleSoft** [comment]
@kadaj Thanks! This seems to be an edge-case that we haven't considered yet. I'll look into it.

**Comment by MaKleSoft** [comment]
There have been significant changes to the user experience in 2.0, so this issues doesn't really apply anymore. Let me know if you find a similar problem in 2.0 (once it's released).
