### ISSUE TITLE
Create integrations with other services to store padlock database file

### ISSUE THREAD

**Issue by moodysalem** [MaKleSoft/padlock#65]
In particular I'd like to see integrations with dropbox and s3 as options for synchronizing files

**Comment by gnacho** [comment]
I'd suggest to support another open source plattforms, such as Owncloud or Seafile.

**Comment by MaKleSoft** [comment]
Duplicate: https://github.com/MaKleSoft/padlock/issues/56
Probably not gonna happen anytime soon, if ever. Sorry!

**Comment by moodysalem** [comment]
@MaKleSoft I think my ideal back end would be GitHub actually.
Repository access is controlled by GitHub (so I can point it at a private repository OR an organization repository once I've logged in), plus you'd get free database file versioning.

Consider changing your model to one time payment for the app! That's how most password storage services charge.
