### ISSUE TITLE
Lost cloud connection

### ISSUE THREAD

**Issue by AndreScherl** [MaKleSoft/padlock#7]
Hello MaKleSoft,

I use padlock on some devices and I like it!
Unfortunately I the devices running the chrome app loose the connection to the padlock cloud after a restart of chrome.
I invite you to have a beer if you fix this issue ;-)

Best regards,
Andre

**Comment by ifraixedes** [comment]
I have always had the same issue.

My current chrome version is 44.0.2403.157, running on OSX 10.10

**Comment by anandubajith** [comment]
I think i also have the same issue. I had to re-login almost every time i open Padlock to Sync with cloud.

**Comment by ifraixedes** [comment]
With last update which I can appreciate with changes in UI, I've realised that I haven't needed to reconnect to padlock cloud service several times; I did one after the updated and so far it hasn't lost the connection

**Comment by MaKleSoft** [comment]
@ifraixedes Cool, let me know if the problem occurs again. Closing this issue for now.
