### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by xunilarium** [MaKleSoft/padlock#71]
Hi
Is there any way to backup database (instead of export to CSV file) and use it some where else (like in my phone)?

**Comment by MaKleSoft** [comment]
Yes, there is! For one, if you want to simply export your data without exposing it in plain text, you can do an encrypted export. Simply choose the 'encrypted' option from the dropdown in the export screen. Another option is Padlock Cloud, which allows you to upload your data to a server and synchronise it with your other devices over the Internet. To connect your device with Padlock Cloud, simply go to Settings > Padlock Cloud and follow the instructions. Let me know if you have any more questions!
