### ISSUE TITLE
Add Internationalization

### ISSUE THREAD

**Issue by LasmGratel** [MaKleSoft/padlock#72]
Padlock is a popular program now, many people around the world use it, but **it's only in English and not able to change the language**.
I suggest to add the **internationalization support**, so **you can find translators to translate it into their languages**.
For example, use java properties file:
`padlock.title=Padlock`
or you can try Gettext file:
`msgid "Padlock"`

**Comment by MaKleSoft** [comment]
Hi @LasmGratel. Thanks for the advice! Yes, internationalisation is definitely something that we've been putting off for too long. It's gonna be one of the major milestones for 2.0 for sure.

**Comment by LasmGratel** [comment]
That should be good.

**Comment by MaKleSoft** [comment]
Internationalization is now supported. Translation files reside under `resources/translations`. Currently there are only German translations. We'll be gradually adding more in the future.
