### ISSUE TITLE
Change font that can easily distinguish between 0 and O

### ISSUE THREAD

**Issue by kadaj** [MaKleSoft/padlock#74]
If would be great if padlock can have a font that makes 0 and O more distinguishable. A slashed zero would make it easier. Thanks.

**Comment by MaKleSoft** [comment]
@kadaj Yep, already on the shortlist for the next release ;)

**Comment by kadaj** [comment]
Cool! Thank you.

**Comment by MaKleSoft** [comment]
Implemented in the `v2.0` branch, so I'm closing this.
