### ISSUE TITLE
Renaming Fields

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#75]
Need an option to rename a field

Everytime I make a new record I find myself deleting both fields just to have "Email" on top of password

**Comment by MaKleSoft** [comment]
@eorroe I feel your pain. The whole UX for editing fields needs to be improved a lot. Most of this will probably be changed drastically as part of the 2.0 rewrite and I'm sure I'll be able to come up with a better UX in the second iteration.

**Comment by MaKleSoft** [comment]
This has already been implemented in the `v2.0` branch, so I'm closing this. I think you'll like the new UX ;)
