### ISSUE TITLE
Firefox WebExtension

### ISSUE THREAD

**Issue by pmk1c** [MaKleSoft/padlock#76]
I'd really like to have this extension for Firefox. Since this is a WebExtension, it shouldn't be too complicated. Or are any APIs, not implemented in Firefox, blocking this?

**Comment by MaKleSoft** [comment]
@pmk1c browser integrations are a complicated topic. For some previous discussion, check out https://github.com/MaKleSoft/padlock/issues/66. Feel free to weigh in there. Closing this issue as duplicate.
