### ISSUE TITLE
Suggest copying after generating password

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#77]

**Comment by MaKleSoft** [comment]
@eorroe I've had the same thought. What do you think the ux should look like? I don't want to use a dialog since that seems too interruptive. Maybe just copy it by default?

**Comment by eorroe** [comment]
I was thinking copy by default, but I think just showing the menu that shows when you click a field, but only showing the copy button

**Comment by MaKleSoft** [comment]
The UX for generating a new password will be completely revamped with 2.0, so this issue probably won't be relevant anymore. We can revisit once you've had a chance to test the new flow.

**Comment by eorroe** [comment]
Intersting
