### ISSUE TITLE
Warn on closing

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#78]
Hey just happened to me like 30s ago and thought to open an issue on it 😉 I was creating a new record, and then scrolled my mouse a little too far and clicked fast on the exit button, which means having to sign back in etc. I think a warning to close might help. Not sure if it should be everytime the button is pressed (I don't think it'll be that introusive) or it should be when making a new record. I'd go with the former.

**Comment by MaKleSoft** [comment]
Just to be clear - which exit button do you mean? The one on window (the little 'x') or the back button on the header? I.e. are you talking about closing the app altogether or just closing the record view?

**Comment by eorroe** [comment]
Closing the app altogether

**Comment by MaKleSoft** [comment]
It's not common for apps to show a close warning unless there are unsaved changes that would get lost. Padlock saves changes automatically as they are performed so there usually shouldn't be any unsaved changes. Closing this as "won't fix".
