### ISSUE TITLE
Import/Export from/to file

### ISSUE THREAD

**Issue by adamhill1988** [MaKleSoft/padlock#80]
Please add the ability to Import/Export directly from/to a file rather than having to copy/paste, its a pain copy and pasting in android.

Thanks Adam

**Comment by MaKleSoft** [comment]
@adamhill1988 I hear you. This is planned for 2.0

**Comment by MaKleSoft** [comment]
Starting with `2.0`, importing/exporting from file is supported for the desktop app at least.
