### ISSUE TITLE
Fast edit for Fields

### ISSUE THREAD

**Issue by AGPHeaddikilla** [MaKleSoft/padlock#81]
Hello,

maybe it would be good for the handling within the program if there would be a function for the double click event on a field. After the double click, the field is editable.
Also a key binding for edititing a specific field would be good.

VH.

**Comment by MaKleSoft** [comment]
@AGPHeaddikilla the editing of fields has been completely overworked for v2.0, making it much more straightforward to edit fields. I think you'll like the new UX!
