### ISSUE TITLE
Multiple usability features requesting

### ISSUE THREAD

**Issue by LanKing** [MaKleSoft/padlock#85]
First of all, thank you for good software. I tried it (adding mine passwords and credit cards) and saw some troubles, that did not give comfort using. Requesting the next features:

- Search process: If needle substring occured in categories and in items, show items first
- Change fields priority
Create fields without titles or create multiline fields with ability to copy one row (for example, I want to add credit card, separated by spaces /readable format/ and concatinated variant. On some sites need to be concatinated.
- Ability to add more than one category or tags
- Usergroups with tabs (for example, work \ private)
- Icon in tray (windows)
- Configurable flag "autohide" for some super-secure fields.

**Comment by MaKleSoft** [comment]
Hi @LanKing! Thanks for your feedback! I'll think about your suggestions. Closing this as it's not an issue or specific feature request. In the future, please create individual tickets for any issues or feature requests, including a detailed description of the problem or feature you want addressed.
