### ISSUE TITLE
Windows and Android APP dont connect to Custom Server

### ISSUE THREAD

**Issue by eduardo-roberto** [MaKleSoft/padlock#87]
Fist: Sorry for my English

Second: Nice project! As soon as possible I will make a donation. 

After cors: true, i can synchronize to my custom server instance using chrome... but i cant synchronize with windows and android app: I got that message: "Failed to connect to Padlock Cloud. Please check your internet connection and try again".

**Comment by MaKleSoft** [comment]
@eduardo-roberto As you mentioned in #88, the problem is probably with the self-signed certificate. Have you been able to get a certificate via LetsEncrypt?

**Comment by eduardo-roberto** [comment]
I dont know how i'll create a LetsEncrypt certificate using my Windows Server VM inside an Enterprise infrastructure (Proxy, FW.. etc..);

I'm studying how I'm going to do this.

**Comment by eduardo-roberto** [comment]
One of the complications is that I'm using a no-ip (DDNS) server DNS to redirect external traffic to my internal network.
Anyway... I'm studying how to solve this.

**Comment by MaKleSoft** [comment]
@eduardo-roberto I hope you don't mind if I close this for now since it's not clear that this is a problem with Padlock (self-signed certificates are simply not supported right now). Let me know what you find once you've obtained a certificate.

**Comment by mitras2** [comment]
I have tried to setup a Padlock-Cloud server on my RasPi a whole day now. Currently the last thing I fail with is, that i am not allowed to use selfsigned certificates EVEN IF THEY ARE IMPORTED ON MY SYSTEM. I tried to import my selfsigned cert on my Linux machine an on my android. And still in both cases the app does not connect (for security issues)...
While i do not want the app to handle all the certificate-stuff on it's own, it would be really good (neccessary) to accept the certificates that arr imported to the base system!

Thanks again for your work
mitras2

**Comment by MaKleSoft** [comment]
@mitras2 Sorry to hear you've had a less-than-smooth experience setting this up! Unfortunately supporting self-signed certificates without compromising security is far from trivial and considering the relatively small number of users this is actually relevant for it's unlikely we'll get around to implementing this any time soon. Any reason why something like LetsEncrypt won't work for you?

**Comment by mitras2** [comment]
It's true. The number of users that are in need of selfsigned certs is probably small. I tried using a LetsEncrypt certificate. But as I use a subdomain of a DNS service, I always end up in LetsEncrypts Rate-Limit blocking me from the certificate...
Maybe an option to trust the system-trusted certificates would be more convenient to implement? Most users won't install any certificates by hand and the few that do chose carefully which certificate to trust.
