### ISSUE TITLE
Cannot connect to custom server using OS X

### ISSUE THREAD

**Issue by Malalicious** [MaKleSoft/padlock#88]
Similar issue to #87, however the following scenario is the case:
- Padlock Cloud running and web interface can be reached from every device I own
- Windows and iOS app connect to the custom padlock cloud server and data gets synchronized
- OS X app throws an error saying "Failed to connect to Padlock Cloud..."

There are no error logs to inspect, as far as I could see. Hard to troubleshoot this issue.
Things I have tried:
- Waiting 48 hours to see if DNS was an issue
- Flush DNS cache
- Reinstall Padlock Cloud
- Change port and hostname of Padlock Cloud
- cors set to true

None of the above helped or solved the issue.

**Comment by eduardo-roberto** [comment]
@Malalicious , did you do something different to sync Windows and iOS App to you custom server? 

Are you using a "valid/oficial" ssl/tls certificate? and https? i think my problem at #87 is because I'm using a self-signed certificate.

**Comment by Malalicious** [comment]
I am using a Let's Encrypt certificate. It works on Windows and iOS so it technically should work on OS X as well but that's sadly not the case!

**Comment by eduardo-roberto** [comment]
@Malalicious can you tell how you create a LetsEncrypt certificate ? i'm using windows and the goserver embed att padlock-cloud. I tried and could not create the certificate.

**Comment by Malalicious** [comment]
https://certbot.eff.org/all-instructions/

Use the official documentation and use the standalone option.

**Comment by MaKleSoft** [comment]
@Malalicious Hm, if you're using a lets encrypt cert and the cors flag then I'm not sure what else might be the problem here. Let me see if I can reproduce the issue. @eduardo-roberto Thanks for trying to help get to the bottom of this!

**Comment by Malalicious** [comment]
Is there a way to observe logs? Or find out WHY it doesn't connect? That'd be pretty useful in this case!

**Comment by MaKleSoft** [comment]
The `padlock-cloud runserver` command should write logs to standard output, unless you configured it to log to a file. If you don't see any logs that means that the server never receives any requests.

**Comment by Malalicious** [comment]
Nothing in the logs indicate that a connection attempt was made. The OS X does not even try to connect. It instantly throws "Failed to connect". Windows and iOS were on "connecting" for a few seconds.

**Comment by MaKleSoft** [comment]
So it seems like problem is either with the client or with the connection. I'm sorry, I know the default error message isn't very helpful. Unfortunately, I can't reproduce the problem on my side. Maybe you can try if it works with in 2.0? Simply pull the latest and then run
```sh
npm install
npm run app
```
Make sure to create a backup of your data first, though, v2.0 is still in alpha. If it doesn't work, 2.0 supports a debug mode as well:
```sh
npm run app -- --debug
```
This will open the web inspector so you can see the raw error logs.

**Comment by Malalicious** [comment]
In v2.0 connecting is fine. A minor (visual) bug that says, after connecting, that "Something went wrong" while synchronizing. After restarting the app, it did actually synchronize.

I have to add, it only seems to build using NodeJS 7.10. 5.XX, 6.XX and 8.XX did NOT work. How does one build the app?

**Comment by MaKleSoft** [comment]
Node 8 should definitely be supported. Can you post the output? (Maybe
create a new issue for that)

**Comment by Malalicious** [comment]
This was apparently a separate issue, unrelated to Padlock. The solution was accepting Xcode's license agreement.
