### ISSUE TITLE
2.0 Alpha: Synchronization with padlock cloud not working

### ISSUE THREAD

**Issue by Malalicious** [MaKleSoft/padlock#89]
Synchronization with padlock cloud seems to be broken in 2.0. The web inspector shows a 405 error code as a response to the POST. Initially it did synchronize (fetched all entries from the server) with an error message "Something went wrong" however it does not synchronize now after adding a new entry.

405:
```
error:
"method_not_allowed"
message:
"Method Not Allowed"
```

**Comment by MaKleSoft** [comment]
Are you using the latest version of padlock cloud? Note that the official server (`cloud.padlock.io`) is not updated to the latest version yet. `cloud-dev.padlock.io` should work with 2.0.

**Comment by Malalicious** [comment]
I am using a custom server setup using https://github.com/MaKleSoft/padlock-cloud.

**Comment by MaKleSoft** [comment]
Can you make sure you are using the latest? Try
```sh
go get -u github.com/maklesoft/padlock-cloud
```
Then restart the server.

**Comment by Malalicious** [comment]
Issuing the above command solved it.
