### ISSUE TITLE
Padlock window focus

### ISSUE THREAD

**Issue by rphcrosbyhf** [MaKleSoft/padlock#98]
Switching between chrome and padlock on macOS is quite frustrating because both applications show up when using Cmd+Tab, but selecting Chrome actually focusses Padlock.

**Comment by rphcrosbyhf** [comment]
It seems similar apps have the same problem: https://github.com/postmanlabs/postman-app-support/issues/1009

**Comment by MaKleSoft** [comment]
I'm assuming you're talking about the app downloaded from the Chrome Web Store? The standalone  versions built with Electron don't have this problem: https://github.com/MaKleSoft/padlock/releases (Note that all the versions there are still beta or alpha, but that will change very soon).
